### PR TITLE
Fixes #17 (function keys)

### LINKED ISSUE #17: Lafayette break fn+f1-12 on lenovo t440s
Hey,
j'ai constate un soucis lorsque j'utilise le layout lafayette sur mon portable,
les touches fn-f1-12 ne répondent plus, je précise que ces touches fonctionnent sur bepo ( mon ancien layout) et qwerty que j'utilise actuellement.

Pour le clavier, c'est un peu une spécificité des nouveau thinkpad et par défaut les touches f1-12 sont désactives et on a accès aux touches utilitaires (son/luminosité/wifi/etc) en direct, mais comme je préfère garder f1-12 en accès direct il est possible de switcher le comportement, par le shortcut 'ctrl - shift - escape' et a partir de ce moment la diode de la touche fn reste allumée et applique les changements suivants
- La touche fn deviens ctrl
- La touche ctrl devient fn
- Il faut faire fn-f1-12 pour activer les touches 'utilitaires'.

Je pense que c'est la touche fn qui ne renvoie pas la même chose, cf mon 'xev' de cette touche.
En qwerty
KeyPress event, serial 33, synthetic NO, window 0x1e00001,
    root 0xd6, subw 0x1202160, time 17789716, (891,185), root:(892,206),
    state 0x10, keycode 151 (keysym 0x1008ff2b, XF86WakeUp), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

En lafayette
KeyRelease event, serial 33, synthetic NO, window 0x1e00001,
    root 0xd6, subw 0x1202169, time 17875110, (640,645), root:(641,666),
    state 0x10, keycode 151 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

J'essaye de tester les comparaison des xkb qwerty / lafayette pour voir ce quil manque.

### PR DESCRIPTION
**Pull request by pandark**

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Sorry to be late at the party, but it didn't work on t440 or x260,
I upgrade my tree with the last MASTER (7aa400b), then cherry-pick your commit,
it build well, but do not want to be installed.
```
$ make clean
rm -f dist/*
$ make
python3 script/make.py layout/*.yaml layout.dev/*.yaml
... dist/dvorak-l.klc
... dist/dvorak-l_utf8.klc
... dist/dvorak-l.keylayout
... dist/dvorak-l.xkb
... dist/qwerty-l.klc
... dist/qwerty-l_utf8.klc
... dist/qwerty-l.keylayout
... dist/qwerty-l.xkb
... dist/qwerty42.klc
... dist/qwerty42_utf8.klc
... dist/qwerty42.keylayout
... dist/qwerty42.xkb
... dist/qwerty42.klc
... dist/qwerty42_utf8.klc
... dist/qwerty42.keylayout
... dist/qwerty42.xkb
$ xkbcomp -w9 dist/qwerty-l.xkb $DISPLAY
Error:            Can't find file "pc" for keycodes include
                  Exiting
                  Abandoning keycodes file "(null)"
```
I run xbcomb-1.3.0, @pandark I suppose the commit fix the bug on your setup do you have a different version or xkb ?

**Comment by pandark** [comment]
Does it work with `us+inet(evdev)`?

**Comment by GuillaumeSeren** [comment]
@pandark Thank's for the reply,
no I get a similar error
```
Error:            Can't find file "us" for keycodes include
                  Exiting
                  Abandoning keycodes file "(null)"
```

**Comment by fabi1cazenave** [comment]
Je crois que je vais renoncer à proposer des fichiers XKB à utiliser en user-space. Quelqu’un peut-il me confirmer que l’installeur résoud ce problème ? https://github.com/fabi1cazenave/qwerty-lafayette/issues/15#issuecomment-379590043

**Comment by GuillaumeSeren** [comment]
Ah un 'installateur' c'est nouveau ca je vais regarder cette diablerie !

**Comment by GuillaumeSeren** [comment]
Répondu de l'autre coté.

**Comment by fabi1cazenave** [comment]
L’installeur résoud le problème. Tant pis pour le fonctionnement en user-space…

**Comment by sebastianoconnell** [comment]
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc104
layout:     us
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)
geometry:   pc(pc104)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+inet(evdev)"     };
        xkb_geometry  { include "pc(pc104)"     };
};

**Pull request closed without merging**
